/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package last1;

import javafx.scene.paint.Color;

/**
 *
 * @author Hmc
 */
public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollBar3 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollBar1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jScrollBar1.setMaximum(150);
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                rgb(evt);
            }
        });
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(290, 77, 500, 30);

        jScrollBar2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jScrollBar2.setMaximum(150);
        jScrollBar2.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar2.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                rgb(evt);
            }
        });
        getContentPane().add(jScrollBar2);
        jScrollBar2.setBounds(290, 237, 500, 30);

        jScrollBar3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jScrollBar3.setMaximum(150);
        jScrollBar3.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar3.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                rgb(evt);
            }
        });
        getContentPane().add(jScrollBar3);
        jScrollBar3.setBounds(290, 377, 500, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 48)); // NOI18N
        jLabel1.setText("Red");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 60, 120, 50);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 48)); // NOI18N
        jLabel2.setText("green");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 220, 120, 50);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 48)); // NOI18N
        jLabel3.setText("blue");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 360, 120, 50);

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setCaretColor(new java.awt.Color(204, 204, 255));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(810, 130, 110, 50);

        jTextField2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setCaretColor(new java.awt.Color(204, 204, 255));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(820, 280, 110, 50);

        jTextField3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setCaretColor(new java.awt.Color(204, 204, 255));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(820, 410, 110, 50);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(580, -40, 10, 10);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(520, 470, 180, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rgb(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_rgb
        // TODO add your handling code here:
       
        
        
        
        
        
        
        int r;
        int g;
        int b;
        r=jScrollBar1.getValue();
        g=jScrollBar2.getValue();
        b=jScrollBar3.getValue();
        
        jTextField1.setText(" "+r);
        jTextField2.setText(" "+g);
        jTextField3.setText(" "+b);
       
        
        
        
        
        Color c = new Color(r, g ,b );
       
        
        setBackground(c);
       
        
        
        
        
        
        
    }//GEN-LAST:event_rgb

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void setBackground(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Color newColor(int r, int g, int b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setBackground(last1.color c) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
