/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DATA_ATTEMP;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Hmc
 */
public class DATA_ATTEMP_1 extends javax.swing.JFrame {
Connection con;
Statement stmt;
    /**
     * Creates new form DATA_ATTEMP_1
     */
    public DATA_ATTEMP_1() {
        initComponents();
        connect();
    }
public void connect(){

    try {
      con=   DriverManager.getConnection("jdbc:mysql://localhost:3306/db1","root","");
      stmt=con.createStatement();
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ENter student id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(111, 32, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ENter student name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(111, 111, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter symester");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(111, 199, 210, 30);

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(410, 30, 260, 30);

        jTextField2.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(410, 106, 260, 30);

        jTextField3.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(410, 180, 260, 30);

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 290, 130, 50);

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jButton2.setText("modify");
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 290, 110, 50);

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 290, 120, 50);

        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(540, 290, 120, 50);

        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 24)); // NOI18N
        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(730, 290, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
     String sid =  jTextField1.getText();
        
      String sn=  jTextField2.getText();
        
        
     String ss=   jTextField3.getText();
        
        
        
     
    try {  String sql="insert into student values("+sid+ ",'" +sn+"','"+ss+ "')"; 
       int n=   stmt.executeUpdate(sql);
       if(n==1){
       
       JOptionPane.showMessageDialog(this, "n rocord saveed successfully");
       }
     
    } catch (SQLException ex) {
      JOptionPane.showMessageDialog(this, ex.getMessage());
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATA_ATTEMP_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATA_ATTEMP_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATA_ATTEMP_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATA_ATTEMP_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATA_ATTEMP_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
